name: OreReplacerPlugin
main: io.github.kuohsuanlo.orereplacer.OreReplacerPlugin
version: ${version}
commands:
  ortoggle:
    description: .
    usage: 
permissions:
    orereplacer.toggle:
        description: player with his node could toggle the plugin's replacing function.
        default: op