name: OreReplacerPlugin
main: io.github.kuohsuanlo.orereplacer.OreReplacerPlugin
commands:
  orereplacer:
    description: .
    usage: 
permissions:
    orereplacer.toggle:
        description: player with his node could toggle the plugin's replacing function.
        default: op
    orereplacer.reload:
        description: player with his node could reload the plugin's config.
        default: op